### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by dougbrouwer** [jessicalh/ekmmeters#1]
We did a virgin pip install ekmmeters on Jamie's Mac, and we need to also do a pip install enum. Can the enum install be rolled into the ekmmeters install?

**Comment by jessicalh** [comment]
Was this with 1.3 or 1.4, or an earlier version?  I just did a project search and cannot find an "import enum" anywhere, and did a pip on a test collector to be sure.  importlib however needs to come out and go in the SQL Server example..

**Comment by jessicalh** [comment]
OK, I've installed and reinstalled and I cannot replicate.   please "pip uninstall" enums and retry.

Please note that if you ran setup py on a very early pre-pypi version or locally, your python library may point to an earlier version.  If this can replicate, it would be helpful to remote in.  Closing now but we can reopen if appropriate.
