### ISSUE TITLE
Constants: Max Demand Interval

### ISSUE THREAD

**Issue by dougbrouwer** [jessicalh/ekmmeters#4]
If this can be labeled MaxDemandResetInterval or MaxDmdResetInt I think it would be more clear what it does.

**Comment by jessicalh** [comment]
MaxDemandReset?  I checked, it was MaxDemandResetInterval to start with. Even with my liking for descriptive names in this library, that seems much but will do if appropriate.  It can also have a note saying that MaxDemandPeriod is the droid they are looking for.  Thoughts?

**Comment by dougbrouwer** [comment]
I think MaxDemandReset should be fairly clear, since it’s associated 
with Monthly, weekly, Daily, and Hourly.

EKM Metering, Inc
www.ekmmetering.com
831-247-4740

**Comment by jessicalh** [comment]
MaxDemandReset was taken by the equivalent of the Dash Now button (next to the interval setting).   This was the original reason for "MaxDemandInterval" as a name. Since that is not OK.. MaxDemandReset is changed to MaxDemandResetIntervalNow and MaxDemandInterval is set to MaxDemandResetInterval

**Comment by dougbrouwer** [comment]
This nomenclature is still confusing, to me. I'm not sure if you fully understand what these settings are doing, or if you got off on the wrong foot because of the Now button in Dash. Maybe this will help clear this up:

If the Reset Max Demand is executed, that means that whatever the max demand wattage is, and it's something that changes over time depending on demand, it gets set to zero. 

Setting Max Demand Interval sets the size of the time window that the max demand measurement uses, 15 min, 30 min, etc.

Setting Max Demand Reset Interval changes the Reset Max Demand from manual to automatic, and determines how often Reset Max Demand gets triggered.

So, calling Reset Max Demand "MaxDemandResetIntervalNow" sounds like setting Max Demand Reset Interval, but it's not. It's really Reset Max Demand.
