### ISSUE TITLE
Constants: Pulse Output Ratio

### ISSUE THREAD

**Issue by dougbrouwer** [jessicalh/ekmmeters#6]
800 and 1600 are also legal output ratios.

Also, this section of Constants is duplicated--it's in twice.

**Comment by jessicalh** [comment]
Adding the ratios.  I don't see the duplication.  Every set of constants has the documentation table above it in reRestructredText -- the source of the table in Sphinx and thence readthedocs.  Is that what you are seeing?  I am only seeing the constant set and the function under this name.

**Comment by jessicalh** [comment]
The duplication is a sphinx issue, unfortunately, and as you pointed out, quite real in the html (assumed it would show up in the header with the table itself).  Will have to try several iterations against readthedocs with other formats.

**Comment by jessicalh** [comment]
Fixed, occured twice in rst file
