### ISSUE TITLE
v3 vs v4

### ISSUE THREAD

**Issue by dougbrouwer** [jessicalh/ekmmeters#8]
I think it would be good to designate v4 only constants

**Comment by jessicalh** [comment]
Per phone call, a documentation only change.  In queue.

**Comment by jessicalh** [comment]
All the examples have been doc'd for version as appropriate, ditto constants.  As some of the docs are embedded in the source, I opted for in-sentence rather than slick formatting.  Still, I think this is addressed.  Closing, please reopen if appropriate.
